const NUTRISME_BUILD = "2026-07-18-1";
document.addEventListener("DOMContentLoaded",()=>{
 const year=document.getElementById("currentYear"); year.textContent=new Date().getFullYear();
 const menu=document.getElementById("menuToggle"),nav=document.getElementById("mainNav");
 menu.addEventListener("click",()=>{const open=nav.classList.toggle("mobile-open");menu.setAttribute("aria-expanded",String(open));});
 document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener("click",()=>nav.classList.remove("mobile-open")));
 const reveals=document.querySelectorAll(".reveal");
 if("IntersectionObserver" in window){const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");obs.unobserve(e.target)}}),{threshold:.12});reveals.forEach(el=>obs.observe(el));}else reveals.forEach(el=>el.classList.add("visible"));
 const modal=document.getElementById("orderModal"),dialog=modal.querySelector(".modal-dialog"),openers=document.querySelectorAll("[data-open-order]"),closers=modal.querySelectorAll("[data-close-order]");
 const selectedPlan=document.getElementById("selectedPlan");let lastFocus=null;
 function openModal(e){lastFocus=document.activeElement;const p=e.currentTarget.dataset.plan;if(p)selectedPlan.value=p;modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";setTimeout(()=>dialog.focus(),20)}
 function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.style.overflow="";if(lastFocus)lastFocus.focus()}
 openers.forEach(b=>b.addEventListener("click",openModal));closers.forEach(b=>b.addEventListener("click",closeModal));document.addEventListener("keydown",e=>{if(e.key==="Escape"&&modal.classList.contains("open"))closeModal()});
 const form=document.getElementById("orderForm"),fullName=document.getElementById("fullName"),instagram=document.getElementById("instagram"),address=document.getElementById("address"),phone=document.getElementById("phone"),consent=document.getElementById("consent"),submit=document.getElementById("submitOrder"),status=document.getElementById("formStatus"),success=document.getElementById("orderSuccess"),formView=document.getElementById("orderFormView"),reset=document.getElementById("resetOrder"),website=document.getElementById("website");
 const normalizePhone=v=>String(v||"").replace(/\D/g,"").replace(/^62/,"").replace(/^0/,"").slice(0,15);phone.addEventListener("input",()=>phone.value=normalizePhone(phone.value));
 const normalizeIg=v=>String(v||"").trim().replace(/^@/,"");instagram.addEventListener("input",()=>instagram.value=normalizeIg(instagram.value));
 const valid={fullName:()=>fullName.value.trim().length>=3,instagram:()=>/^[A-Za-z0-9._]{2,50}$/.test(normalizeIg(instagram.value)),address:()=>address.value.trim().length>=10,phone:()=>/^8\d{7,14}$/.test(normalizePhone(phone.value)),consent:()=>consent.checked};
 const fields={fullName:fullName.closest("[data-field]"),instagram:instagram.closest("[data-field]"),address:address.closest("[data-field]"),phone:phone.closest("[data-field]")};
 function mark(k,force=false){const ok=valid[k]();if(fields[k])fields[k].classList.toggle("invalid",!ok&&(force||document.getElementById(k).value.length>0));return ok}
 function update(){const ok=valid.fullName()&&valid.instagram()&&valid.address()&&valid.phone()&&valid.consent();submit.disabled=!ok;status.textContent=ok?"Data lengkap. Silakan kirim formulir.":"Lengkapi seluruh data dan persetujuan."}
 [fullName,instagram,address,phone].forEach(i=>{i.addEventListener("input",()=>{mark(i.id);update()});i.addEventListener("blur",()=>mark(i.id,true))});consent.addEventListener("change",update);update();
 const APPS_SCRIPT_URL="https://script.google.com/macros/s/AKfycbxN0ZfvGFX1RPp8pFj4Afxk1Q3JECumWYuaZYel8PY-Fc4OvleOvyzHSq_Ljr1sx69X/exec";
 form.addEventListener("submit",async e=>{e.preventDefault();const checks=[mark("fullName",true),mark("instagram",true),mark("address",true),mark("phone",true),valid.consent()];if(!checks.every(Boolean)){status.textContent="Periksa kembali data yang belum valid.";return}submit.disabled=true;submit.setAttribute("aria-busy","true");status.textContent="Mengirim data...";try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);await fetch(APPS_SCRIPT_URL,{method:"POST",mode:"no-cors",cache:"no-store",body:new URLSearchParams({action:"createOrder",build:NUTRISME_BUILD,requestId:(crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random()),nama:fullName.value.trim(),instagram:normalizeIg(instagram.value),alamat:address.value.trim(),telepon:normalizePhone(phone.value),paket:selectedPlan.value,consent:"yes",source:location.href,waktuKlien:new Date().toISOString(),website:website.value.trim()}),signal:controller.signal});clearTimeout(timer);formView.hidden=true;success.hidden=false;dialog.scrollTop=0}catch(err){status.textContent=err.name==="AbortError"?"Pengiriman terlalu lama. Coba lagi.":"Data belum berhasil dikirim. Coba lagi.";submit.disabled=false}finally{submit.removeAttribute("aria-busy")}});
 reset.addEventListener("click",()=>{form.reset();selectedPlan.value="Belum menentukan";Object.values(fields).forEach(f=>f.classList.remove("invalid"));success.hidden=true;formView.hidden=false;update();fullName.focus()});
});
